### ISSUE TITLE
No syntax highlighting on fresh install

### ISSUE THREAD

**Issue by kazimuth** [zigtools/zls-vscode#15]
Hey, I just installed zig master (2020-10-20) and zls-vscode, and while zls seems to connect successfully and completions etc work, there's no syntax highlighting at all:

![hmm](https://user-images.githubusercontent.com/555667/96647578-edc2f400-12fb-11eb-9768-7cc9175f7fee.png)

However, if I override `"editor.semanticHighlighting.enabled"` in my user settings to be `true` rather than `"configuredByTheme"` (the default), syntax highlighting works perfectly.

**Comment by SERWare** [comment]
> Hey, I just installed zig master (2020-10-20) and zls-vscode, and while zls seems to connect successfully and completions etc work, there's no syntax highlighting at all:
> 
> ![hmm](https://user-images.githubusercontent.com/555667/96647578-edc2f400-12fb-11eb-9768-7cc9175f7fee.png)
> 
> However, if I override `"editor.semanticHighlighting.enabled"` in my user settings to be `true` rather than `"configuredByTheme"` (the default), syntax highlighting works perfectly.

The same thing happened to me and it was solved this way.

Thanks.

**Comment by emptydiagram** [comment]
I'm experiencing the same issue, except that setting `editor.semanticHighlighting.enabled` = true doesn't fix it.

**Comment by BLucky-gh** [comment]
> I'm experiencing the same issue, except that setting `editor.semanticHighlighting.enabled` = true doesn't fix it.

same here

**Comment by SuperAuguste** [comment]
Semantic highlighting needs to be enabled in-editor and within zls itself too.

**Comment by BLucky-gh** [comment]
> Semantic highlighting needs to be enabled in-editor and within zls itself too.
 I don't know about the others, but I definitely did have semantic highlighting enabled both in editor and zls, though this is an old issue and I don't even remember if I ever fixed it for myself because this was half a year ago.
